---
- name: Deployment of trainapp docker images
  hosts: all
  
  tasks:
    - name: Add community repository
      lineinfile:
        path: /etc/apk/repositories
        regexp: '^#.*v3\.15\/community$'
        line: 'http://dl-cdn.alpinelinux.org/alpine/v3.15/community'
        state: present
        backup: yes

    - name: Install docker on host
      apk:
        name: docker
        state: present

    - name: Start docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install pip
      shell:
        cmd: /usr/bin/python3 -m ensurepip

    - name: Install docker pip dependecies
      pip:
        name: docker
        state: present
