---
- name: Reset database
  hosts: all
  
  tasks:
    - name: Reseed database
      community.docker.docker_container_exec:
        container: trainapp-api
        command: npm run seed
        chdir: /app
