name: Build images
on: [ push ]

env: 
  IMAGE_NAME: 'trainapp-web'
  APP_PATH: './vuefrontend'

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Setup QEMU for docker
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build image and do not push
        uses: docker/build-push-action@v2
        with: 
          context: ${{ env.APP_PATH }}
          tags: someuser/${{ env.IMAGE_NAME }}:latest
          push: false

      - name: Output digest
        run: echo ${{ steps.docker_build.output.digest }}

      - name: Output metadata
        run: echo ${{ steps.docker_build.output.metadata }}
