name: build docker images for release
on: 
  push:
    branches:
      - release

env: 
  IMAGE_BACKEND_NAME: 'backend'
  APP_BACKEND_PATH: './backend'
  IMAGE_FRONTEND_NAME: 'frontend'
  APP_FRONTEND_PATH: './frontend'

jobs:
  build-frontend-image:
    runs-on: ubuntu-latest
    steps:
      - name: Register variables
        run: |
          echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Setup QEMU for docker
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push
        id: docker_build
        uses: docker/build-push-action@v2
        with: 
          context: ${{ env.APP_FRONTEND_PATH }}
          tags: ghcr.io/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_FRONTEND_NAME }}:latest
          push: true

      - name: Output digest
        run: echo ${{ steps.docker_build.output.digest }}

      - name: Output metadata
        run: echo ${{ steps.docker_build.output.metadata }}

  build-backend-image:
    runs-on: ubuntu-latest
    steps:
      - name: Register variables
        run: |
          echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
      - name: Checkout git repo
        uses: actions/checkout@v2

      - name: Setup QEMU for docker
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image and push
        id: docker_build
        uses: docker/build-push-action@v2
        with: 
          context: ${{ env.APP_BACKEND_PATH }}
          tags: ghcr.io/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_BACKEND_NAME }}:latest
          push: true

      - name: Output digest
        run: echo ${{ steps.docker_build.output.digest }}

      - name: Output metadata
        run: echo ${{ steps.docker_build.output.metadata }}
